### ISSUE TITLE
fmg_vm managed_dev defined twice in config.go

### ISSUE THREAD

**Issue by movinalot** [fortinetdev/terraform-provider-fortiflexvm#1]
fmg_vm managed_dev is defined as both 3 and 30

lines 93 and 94
lines 139 and 140

30 is the returned valued on lines 171 and 172

Should the 3 definition on lines 93 and 94 be removed?

**Comment by dux-fortinet** [comment]
Hi movinalot,

You are right. In [FlexVM API](https://fndn.fortinet.net/index.php?/fortiapi/954-fortiflex/), the id of fmg_vm->managed_dev was 3, and now it is 30.
We keep lines 93 and 94 for backward compatibility. 
Keeping line 93 and 94 won't affect the usage, these lines of code are used to parse the data returned by Flexvm API, not send data to API. If FlexVM API return value '3' again one day, our code can handle it without error.
Thanks for pointing it out :)

**Comment by movinalot** [comment]
Sounds good, thank you.
