### ISSUE TITLE
Docs - Example usage for "fortiflexvm_entitlements_vm" update scenario

### ISSUE THREAD

**Issue by AD-GenY** [fortinetdev/terraform-provider-fortiflexvm#2]
Since we have a single resource to create and update entitlements now, it would be great to have an example usage of Update scenario as well 

https://registry.terraform.io/providers/fortinetdev/fortiflexvm/latest/docs/resources/fortiflexvm_entitlements_vm

Thank you !

**Comment by dux-fortinet** [comment]
Will add it in the next release. Thanks for the suggestion.

**Comment by dux-fortinet** [comment]
To update one entitlement, please check [fortiflexvm_entitlements_vm](https://registry.terraform.io/providers/fortinetdev/fortiflexvm/latest/docs/resources/fortiflexvm_entitlements_vm)
To retrieve existing entitlements, please check [fortiflexvm_retrieve_vm_group](https://registry.terraform.io/providers/fortinetdev/fortiflexvm/latest/docs/resources/fortiflexvm_retrieve_vm_group)

Thanks
